### ISSUE TITLE
[WIP] pull request and  bugs while running  .jar manually from cmd line

### ISSUE THREAD

**Issue by LineStettler** [valendinosaurus/lernstickWelcome#4]

**Comment by sschw** [comment]
We have a MissingResourceException in the LernstickTools-library. The jar-File of Lernstick-Tools might not include the bundles under ch.fhnw.util.Strings. 
That causes StorageTools.getSystemStorageDevice to fail. 

We might need to fix the pom file under the repository. https://github.com/valendinosaurus/lernstickTools

The lernstickWelcome-jar might generate correctly...

**Comment by sschw** [comment]
I've added the bundles of the lernstickTools jar. I couldn't test the build process as we still have the problem @tdrdb is working on. I'll check on the build process again today evening as I will take a look at #5

**Comment by LineStettler** [comment]
Bugs are now fixed and the build process works fine with maven
