### ISSUE TITLE
Change Debian package build process to maven

### ISSUE THREAD

**Issue by THS-on** [valendinosaurus/lernstickWelcome#5]
Currently ant is used.
https://wiki.debian.org/Java/Packaging

**Comment by LineStettler** [comment]
build Process is now migrated to maven

**Comment by THS-on** [comment]
This issue is not fixed. If you want to build the Debian package it is build with ant. Have a look at the `debian` directory (https://github.com/valendinosaurus/lernstickWelcome/blob/master/debian/rules).

**Comment by LineStettler** [comment]
it works fine for me and my colleagues. We tested it on different laptops.
 I can build it with mvn package from cmd line and then run the jar or build  it in netbeans, which also uses pom.xml to build the project. The jar file can then be found in the folder "target"

**Comment by THS-on** [comment]
I know that this works, but in the end you want a .deb file to install on your Debian based system. Currently the official way was used by Ronny and used ant to build the package. Learn more here: https://wiki.debian.org/Packaging and https://wiki.debian.org/Java/Packaging
The other way is to use [jdeb](https://github.com/tcurdt/jdeb) to create this package which does not comply with the official way but is easier to implement.

**Comment by THS-on** [comment]
Latest version works fine with `mvn install`. I haven't tested all the features, but I like the new lernstickWelcome. Great work.
Maybe include a README with howto build the package and what dependencies are used.
